---
title: "ggplot2"
output: 
  html_document:
    keep_md: true
date: '2022-06-22'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## ggplot2 강의
- 데이터 불러오기
```{r}

# install.packages("nycflights13")
# install.packages("tidyverse")

library(dplyr)
library(readxl)
library(ggplot2)

library(nycflights13)
library(tidyverse)

who_disease <- read_xlsx("data/who_disease.xlsx")


# 기본 시각화
ggplot(who_disease, aes(x = year, y = cases))+
  # 그래프 종류
  geom_point()

# 옵션 1. 투명도 주기
ggplot(who_disease, aes(x = year, y = cases))+
  # 그래프 종류
  geom_point(alpha = 0.1)

# 옵션 2. 색상 변화
ggplot(who_disease, aes(x = year, y = cases))+
  # 그래프 종류
  geom_point(alpha = 0.1, colour = "red")

ggplot(who_disease, aes(x = year, y = cases))+
  # 그래프 종류
  geom_point(alpha = 0.1, colour = "#F8A821")

?geom_point

```

- colour 입력 위치
  + geom_point(colour=red)
  + aes(x, y, colour = 칼럼명)
  
```{r}
str(iris)
ggplot(iris, aes(x = Sepal.Length,
                 y = Sepal.Width,
                 colour = Species,
                 size = Petal.Length))+
geom_point()
```


- 산점도: x축 수치형 연속형 데이터, y축 수치형 연속형 데이터 
- 
```{r}
ggplot(who_disease, aes(x = year, y = cases))+
  geom_point(alpha = 0.1)
```


- 히스토그램
 + 질병 데이터 region = AMR, year = 1980, disease = 백일해(pertussis)
 case > 0
 
```{r}
library(dplyr)
str(who_disease)
data2 <- who_disease %>%
  filter(region == 'AMR',
         year == 1980,
         disease == 'pertussis',
         cases > 0) -> data2

ggplot(data2, aes(x = cases))+
  geom_histogram()
```
 
명료하지 않다


```{r}
ggplot(data2, aes(x = country, y = cases))+
  geom_col()+
  # 옵션
  coord_flip()
```


```{r}
ggplot(data2, aes(x = country, y = cases))+
  geom_col(fill = "blue")+
  # 옵션
  coord_flip()
```

#산점도 그래프 그리기
```{r}
library(ggplot2)
```


```{r}
diamonds <- ggplot2::diamonds
ggplot(diamonds, aes(x=carat, y=price))+geom_point()
```


```{r}
```

# 막대그래프 그리기
```{r}
table(diamonds$cut)
```
```{r}
ggplot(diamonds, aes(x=cut,y=price))+geom_bar(stat = "identity")
```


## ggplot() 정교하게 그리기 
- 산점도 그리기 
```{r}
diamonds <- ggplot2::diamonds
ggplot(diamonds, aes(x=carat,
                     y=price,
                     col=cut))+
  geom_point()
```

- 막대그래프에 2개 범주 내용 반영하기
```{r}
ggplot(diamonds, aes(x=color))+
  geom_bar()
```

```{r}
ggplot(diamonds, aes(x=color, fill=cut))+
  geom_bar()
```

```{r}
ggplot(diamonds, aes(x=color, fill=cut))+
  geom_bar(position = "fill")
```


- p219
선 그래프에 2개 범주 내용 반영
```{r}
leisure <- read.csv("data/leisure.csv")
str(leisure)
```

```{r}
ggplot(data=leisure, aes(x=age, y=expense))+
  geom_line()
```

```{r}
ggplot(data=leisure, aes(x=age,
                         y=expense,
                         col=sex))+
  geom_line()
```

```{r}
ggplot(data=leisure, aes(x=age,
                         y=expense,
                         col=sex))+
  geom_line(size=1.5, linetype=6)
```


## 막대그래프의 순서변경
- reorder()
```{r}
mpg1 <- read.csv("data/mpg1.csv",
                 stringsAsFactors = F)

# 데이터 가공
drv_hwy <- mpg1 %>% 
  group_by(drv) %>% 
  summarise(mean_hwy=mean(hwy))


```

오름차순
```{r}
ggplot(data = drv_hwy, aes(x=reorder(drv,mean_hwy), y=mean_hwy))+
  geom_col()
```

내림차순
```{r}
ggplot(data = drv_hwy, aes(x=reorder(drv,-mean_hwy), y=mean_hwy))+
  geom_col()
```


```{r}
ggplot(data = drv_hwy, aes(x=drv, y=mean_hwy))+
  geom_col()+
  labs(
    title = "그래프 제목을 입력하세요",
    subtitle = "그래프 소제목을 입력하세요",
    x="x변수명을 입력하세요",
    y="y변수명을 입력하세요",
    caption = "데이터 출처를 입력하세요"
  )

```



